version: '3.9'

services:
  postgres:
    image: postgres:13.3
    container_name: ironfish_postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-compose.sql:/docker-entrypoint-initdb.d/init.sql
    # uncomment below if you want to log queries
    # command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

volumes:
  postgres_data:
