/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/. */
export enum GraphileWorkerPattern {
  ALLOCATION_CREATION = 'ALLOCATION_CREATION',
  CREATE_EVENT = 'CREATE_EVENT',
  CREATE_NODE_UPTIME_EVENT = 'CREATE_NODE_UPTIME_EVENT',
  DELETE_BLOCK_MINED_EVENT = 'DELETE_BLOCK_MINED_EVENT',
  LOAD_ASSET_DESCRIPTIONS = 'LOAD_ASSET_DESCRIPTIONS',
  REFRESH_DEPOSIT = 'REFRESH_DEPOSIT',
  REFRESH_DEPOSITS = 'REFRESH_DEPOSITS',
  REFRESH_NATIVE_ASSET_SUPPLY = 'REFRESH_NATIVE_ASSET_SUPPLY',
  REFRESH_POOL_4_POINTS = 'REFRESH_POOL_4_POINTS',
  REFRESH_USERS_POINTS = 'REFRESH_USERS_POINTS',
  REFRESH_USER_POINTS = 'REFRESH_USER_POINTS',
  REFRESH_USERS_REDEMPTION = 'REFRESH_USERS_REDEMPTION',
  REFRESH_USER_REDEMPTION = 'REFRESH_USER_REDEMPTION',
  SUBMIT_DEPOSITED_IRON_TO_TELEMETRY = 'SUBMIT_DEPOSITED_IRON_TO_TELEMETRY',
  SYNC_BLOCKS_DAILY = 'SYNC_BLOCKS_DAILY',
  UPDATE_LATEST_POINTS = 'UPDATE_LATEST_POINTS',
  UPDATE_USER_RANKS = 'UPDATE_USER_RANKS',
  UPSERT_BLOCK_MINED_EVENT = 'UPSERT_BLOCK_MINED_EVENT',
  UPSERT_DEPOSIT = 'UPSERT_DEPOSIT',
}
