name: MAINNET - Deploy API
on: workflow_dispatch

jobs:
  deploy:
    name: Promote Testnet API
    runs-on: ubuntu-latest

    steps:
      - name: Promote Testnet
        uses: tiltshift/heroku-promote-app@v1
        with:
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_TESTNET }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
