name: ARCHIVE - Deploy Phase 3 API
on:
  push:
    branches:
      - phase3

jobs:
  deploy:
    name: Deploy Phase 3 API
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_app_name: ironfish-api-phase3
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
